export const config = {
    nutrition: {
        significantDifferencePercent: 20,
        minimumRelevantMicronutrientsForWarning: 4,
        relevantMicronutrientTerms: [
            "vitamina",
            "retinol",
            "tiamina",
            "riboflavina",
            "niacina",
            "piridoxina",
            "folato",
            "acido folico",
            "biotina",
            "cobalamina",
            "calcio",
            "ferro",
            "magnesio",
            "fosforo",
            "sodio",
            "potassio",
            "zinco",
            "cobre",
            "manganes",
            "selenio",
            "iodo",
            "cromo",
            "molibdenio",
            "cloro",
            "fluor",
        ],
    },
    dashboard: {
        monthsInOverview: 6,
        recentPatientsLimit: 5,
        planDistribution: {
            noPlan: 0,
            onePlan: 1,
            twoPlans: 2,
            threeOrMoreMinimum: 3,
        },
    },
} as const;
