import { CalendarDays, FileText, Plus, Users } from "lucide-react";

export default function ProductPreview() {
  return (
    <div className="overflow-hidden rounded-lg border border-border-default bg-surface-default shadow-md motion-safe:animate-in motion-safe:fade-in motion-safe:slide-in-from-bottom-4 motion-safe:duration-500" aria-label="Demonstracao visual da area de pacientes do Nutri Plan">
      <div className="flex items-center justify-between border-b border-border-default bg-surface-muted px-4 py-3"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-brand-400" /><span className="h-2.5 w-2.5 rounded-full bg-border-strong" /><span className="h-2.5 w-2.5 rounded-full bg-border-strong" /></div><span className="text-caption font-medium text-content-muted">nutriplan.app</span></div>
      <div className="grid min-h-105 grid-cols-[10rem_1fr]">
        <aside className="hidden border-r border-border-default bg-background-subtle p-4 sm:block"><div className="flex items-center gap-2 text-body-small font-bold text-content-primary"><span className="flex h-7 w-7 items-center justify-center rounded-md bg-action-primary text-caption text-action-primary-text">N</span> Nutri Plan</div><div className="mt-8 space-y-2 text-caption font-medium text-content-secondary"><p>Inicio</p><p className="rounded-md bg-brand-50 px-2 py-2 text-action-primary">Meus pacientes</p><p>Meu perfil</p><p>Receitas</p></div></aside>
        <div className="min-w-0 p-4 sm:p-6"><div className="flex flex-col gap-3 border-b border-border-subtle pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-caption font-semibold uppercase text-content-secondary">Pacientes</p><h2 className="mt-1 text-heading-h3 font-bold text-content-primary">Meus pacientes</h2><p className="mt-1 text-caption text-content-muted">Acompanhe planos e informacoes cadastradas.</p></div><span className="inline-flex h-9 items-center justify-center rounded-md bg-action-primary px-3 text-caption font-semibold text-action-primary-text"><Plus className="mr-1 h-3.5 w-3.5" /> Novo paciente</span></div>
          <div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="border border-border-default p-3"><p className="text-caption text-content-secondary">Pacientes</p><p className="mt-2 text-heading-h3 font-semibold text-content-primary">Sua base</p></div><div className="border border-border-default p-3"><p className="text-caption text-content-secondary">Planos</p><p className="mt-2 text-heading-h3 font-semibold text-content-primary">Organizados</p></div><div className="border border-border-default p-3"><p className="text-caption text-content-secondary">Atendimento</p><p className="mt-2 text-heading-h3 font-semibold text-content-primary">Em foco</p></div></div>
          <div className="mt-5 overflow-hidden border border-border-default"><div className="grid grid-cols-[1fr_auto] gap-4 bg-surface-muted px-4 py-3 text-caption font-semibold text-content-secondary"><span>Paciente</span><span>Planos</span></div>{["Acompanhamento alimentar", "Plano de rotina", "Orientacoes gerais"].map((label, index) => <div key={label} className="grid grid-cols-[1fr_auto] items-center gap-4 border-t border-border-subtle px-4 py-3"><div className="flex min-w-0 items-center gap-2"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-brand-100 text-action-primary"><Users className="h-3.5 w-3.5" /></span><div className="min-w-0"><p className="truncate text-caption font-semibold text-content-primary">Paciente {index + 1}</p><p className="mt-0.5 truncate text-caption text-content-muted">{label}</p></div></div><span className="inline-flex items-center gap-1 text-caption text-content-secondary"><FileText className="h-3.5 w-3.5" /><CalendarDays className="hidden h-3.5 w-3.5 sm:block" /></span></div>)}</div>
        </div>
      </div>
    </div>
  );
}
